### ISSUE TITLE
Unable to run 'artisan test' in verbose mode

### ISSUE THREAD

**Issue by miken32** [nunomaduro/collision#279]
Output:
```none
$ ./artisan test --verbose
PHPUnit 10.2.6 by Sebastian Bergmann and contributors.

Unknown option "--verbose"

$ ./artisan test -vv
PHPUnit 10.2.6 by Sebastian Bergmann and contributors.

Unknown option "-v"

$  ./artisan --verbose test
PHPUnit 10.2.6 by Sebastian Bergmann and contributors.

Test file "test" not found

$  ./artisan -vv test
PHPUnit 10.2.6 by Sebastian Bergmann and contributors.

Test file "test" not found
```

There is some code for adjusting the display based on verbosity that I'd like to use (e.g. in `NunoMaduro\Collision\Writer::getFrames()` or `NunoMaduro\Collision\Style::writeDescriptionLine()`) so I'd guess support for this was accidentally dropped either in this package or Laravel at some point.

Using nunomaduro/collision v7.7.0 with laravel/framework v10.15.0 and filp/whoops v2.15.3

**Comment by nunomaduro** [comment]
Fixed [v7.8.0](https://github.com/nunomaduro/collision/releases/tag/v7.8.0).

**Comment by miken32** [comment]
This was not actually fixed, I don't see any reference to any changes in 7.8 that would have fixed it. Same behaviour persists in 11.5.

**Comment by miken32** [comment]
And still not fixed @nunomaduro. Same output for all commands using 8.8.2 with Laravel 12.34 and Phpunit 12.4.1
